=== LEAF-HQ/LEAF/templates/Configuration.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>


<!ELEMENT Configuration (SubmissionSettings,InputDatasets,AdditionalInputs*,AdditionalVariables)>
<!ATTLIST Configuration
    TargetLumi           CDATA            #REQUIRED
    OutputDirectory      CDATA            #REQUIRED
    SEDirector           CDATA            ""
    PostFix              CDATA            ""
    AnalysisTool         CDATA            #REQUIRED
    NEventsMax           CDATA            "-1"
    NEventsSkip          CDATA            "0"
>


<!ELEMENT SubmissionSettings EMPTY>
<!ATTLIST SubmissionSettings
    EventsPerJob         CDATA            "-1"
    FilesPerJob          CDATA            "-1"
    Walltime             CDATA            "01:00:00"
>

<!ELEMENT InputDatasets (Dataset+)>

<!ELEMENT Dataset (InputFile+)>
<!ATTLIST Dataset
    Name        CDATA       #REQUIRED
    Lumi        CDATA       #REQUIRED
    Type        CDATA       #REQUIRED
    Group       CDATA       #REQUIRED
    Year        CDATA       #REQUIRED
>

<!ELEMENT InputFile EMPTY>
<!ATTLIST InputFile
    FileName    CDATA       #REQUIRED
>

<!ELEMENT AdditionalInputs (AdditionalInput*)>
<!ELEMENT AdditionalInput (AdditionalDataset+,Collection+)>

<!ELEMENT AdditionalDataset (InputFile+)>
<!ATTLIST AdditionalDataset
    Name        CDATA       #REQUIRED
    Year        CDATA       #REQUIRED
>

<!ELEMENT Collection EMPTY>
<!ATTLIST Collection
    ClassName        CDATA       #REQUIRED
    BranchName       CDATA       #REQUIRED
    FileName         CDATA       #REQUIRED
>

<!ELEMENT AdditionalVariables (Variable*)>

<!ELEMENT Variable EMPTY>
<!ATTLIST Variable
    Name        CDATA       #REQUIRED
    Value       CDATA       #REQUIRED
>

=== LEAF-HQ/LEAF/templates/config_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration PUBLIC "" "Configuration.dtd"[


<!ENTITY TargetLumi  "1" >
<!ENTITY outfilepath "$MYLEAFPATH/../../../$MYANALYSISNAME/2017/Preselection/InitialSetup" >
<!-- can also use the storage elements like this example below. If a path starts with "/pnfs/", the Analyzer will prepend the "SEDirector" specified below
<!ENTITY outfilepath "/pnfs/psi.ch/cms/trivcat/store/user/$MYUSERNAME/$MYANALYSISNAME/InitialSetup" >
-->



<!ENTITY TestSignal_M1000        SYSTEM "$MYLEAFPATH/.testsamples/TestSignal_M1000.xml" >
<!ENTITY TestSignal_M2000        SYSTEM "$MYLEAFPATH/.testsamples/TestSignal_M2000.xml" >
<!ENTITY TestBackground_Sample1  SYSTEM "$MYLEAFPATH/.testsamples/TestBackground.xml" >
<!ENTITY TestData_Sample1        SYSTEM "$MYLEAFPATH/.testsamples/TestData.xml" >

<!-- real datasets are here
<!ENTITY LQLQToBTau_MLQ1000_MPS117_MC1100_L1p0   SYSTEM "$MYANALYZERPATH/datasets/UL17/Summer20/MINIAOD/LQLQToBTau_MLQ1000_MPS117_MC1100_L1p0.xml" >
<!ENTITY LQLQToBTau_MLQ1360_MPS117_MC1100_L1p0   SYSTEM "$MYANALYZERPATH/datasets/UL17/Summer20/MINIAOD/LQLQToBTau_MLQ1360_MPS117_MC1100_L1p0.xml" >
<!ENTITY WJetsToLNu_Inclusive                    SYSTEM "$MYANALYZERPATH/datasets/UL17/Summer20/MINIAOD/WJetsToLNu_Inclusive.xml" >
-->



]>


<Configuration OutputDirectory="&outfilepath;" PostFix="" SEDirector="root://t3dcachedb03.psi.ch/" TargetLumi="&TargetLumi;" AnalysisTool="$MYTOOLNAME">

  <SubmissionSettings EventsPerJob="-1" FilesPerJob="-1" Walltime="01:00:00" />

  <InputDatasets>
    <Dataset Name="TestSignal_M1000"        Lumi="100000"    Year="2017"  Type="MC"    Group="None"  >              &TestSignal_M1000;         </Dataset>
    <Dataset Name="TestSignal_M2000"        Lumi="100000"    Year="2017"  Type="MC"    Group="None"  >              &TestSignal_M2000;         </Dataset>
    <Dataset Name="TestBackground_Sample1"  Lumi="100000"    Year="2017"  Type="MC"    Group="TestBackground"  >    &TestBackground_Sample1;   </Dataset>
    <Dataset Name="TestData_Sample1"        Lumi="1"         Year="2017"  Type="DATA"  Group="TestData" >           &TestData_Sample1;         </Dataset>
  </InputDatasets>

  <AdditionalInputs>
    <!--
    Here, additional collections can be specified. Use this format:

    <AdditionalInput>
      <AdditionalDataset Name="TestDataset"   Year="2017" >                 &TestDataset_pfonly;                </AdditionalDataset>
      <Collection ClassName="PFCandidate" BranchName="pfcands"/>
    </AdditionalInput>

    <AdditionalInput>
      <AdditionalDataset Name="TestDataset"   Year="2017" >                 &TestDataset_trigandstandard;                </AdditionalDataset>
      <AdditionalDataset Name="TestDataset2"  Year="2017" >                 &TestDataset_trigandstandard;                </AdditionalDataset>
      <Collection ClassName="TriggerObject" BranchName="triggerobjects"/>
    </AdditionalInput>

    It is possible to define as many <AdditionalInput> fields as desired, one for each new set of files to be read in. Inside each <AdditionalInput>, multiple <Collection> can be defined - one per branch that should be taken from this additional input dataset.

    -->
  </AdditionalInputs>

  <AdditionalVariables>
    <Variable Name="test" Value="testvalue"/>
  </AdditionalVariables>

</Configuration>

=== LEAF-HQ/LEAF/templates/ConfigBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration PUBLIC "" "Configuration.dtd"[

<!ENTITY ModuleName  "ModuleName" >
<!ENTITY OutputDirectory  "$MYLEAFPATH/../../../$MYANALYSISNAME/Year/&ModuleName;/" >

]>


<Configuration OutputDirectory="&OutputDirectory;" PostFix="" SEDirector="root://maite.iihe.ac.be:1094/" TargetLumi="None" AnalysisTool="&ModuleName;Module">

  <SubmissionSettings FilesPerJob="1"/>

  <InputDatasets>
    <Dataset Name="VBF_HToZZTo4L_M125"           Lumi="None" Year="None" Type="None" Group="None"> <InputFile FileName="None"/> </Dataset>
  </InputDatasets>

  <AdditionalVariables>
    <!-- Cleaning -->
    <Variable Name="do_lumisel"       Value="true"/>  <!--true/false -->
    <Variable Name="do_lumiweight"    Value="true"/>  <!--true/false -->
    <Variable Name="do_PUreweight"    Value="true"/>  <!--true/false -->
    <Variable Name="do_metfilters"    Value="true"/>  <!--true/false -->
    <Variable Name="do_jec"           Value="true"/>  <!--true/false -->
    <Variable Name="do_jer"           Value="true"/>  <!--true/false -->
    <Variable Name="do_eleid"         Value="true"/>  <!--true/false -->
    <Variable Name="do_muid"          Value="true"/>  <!--true/false -->
    <Variable Name="do_tauid"         Value="false"/> <!--true/false -->
    <Variable Name="do_jetid"         Value="true"/>  <!--true/false -->
    <Variable Name="do_metcorrection" Value="true"/>  <!--true/false -->

    <!-- Corrections and Systematic uncertainties -->
    <Variable Name="JEC_Version"      Value="None"/>
    <Variable Name="JER_Version"      Value="None"/>
    <Variable Name="jec_systematics"  Value="nominal"/> <!--nominal/down/up -->
    <Variable Name="jer_systematics"  Value="nominal"/> <!--nominal/down/up -->

  </AdditionalVariables>

</Configuration>
